In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

from typing import Generator


# 真实的权重
true_w = torch.tensor([2, -3.4])
# 真实的偏差
true_b = 4.2
# 通过真实的权重和偏差生成样本和标注
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [2]:
batch_size = 10
dataset = data.TensorDataset(features, labels)
# 生成每10个样本为一组的随机数据
data_iter = data.DataLoader(dataset, batch_size, shuffle=True)


for t_data, t_labels in data_iter:
    print(t_data)
    print(t_labels)
    break

tensor([[ 0.7986,  0.4083],
        [ 1.0535,  0.5692],
        [ 1.4239,  0.0616],
        [-0.6981, -0.0916],
        [-0.1833,  0.1798],
        [-0.0858, -0.4625],
        [-0.9639, -0.3333],
        [-0.8729, -0.3595],
        [-0.0774, -0.8647],
        [-0.4119,  0.1894]])
tensor([[4.3770],
        [4.3601],
        [6.8245],
        [3.1094],
        [3.2355],
        [5.5987],
        [3.3936],
        [3.6698],
        [6.9922],
        [2.7377]])


使用框架预定层

In [3]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

初始化模型参数

In [4]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

均方误差使用的函数

In [5]:
loss = nn.MSELoss()

SGD实例

In [6]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

开始整活

In [7]:
for epoch in range(3):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000206
epoch 2, loss 0.000098
epoch 3, loss 0.000098
