## 线代实现

[视频](https://www.bilibili.com/video/BV1eK4y1U7Qy?p=2) | [教材](https://zh-v2.d2l.ai/chapter_preliminaries/linear-algebra.html)

In [1]:
import torch

标量由只有一个元素的张量表示

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

向量

In [3]:
# 可以将向量视为列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
# 通过张量索引元素
x[3]

tensor(3)

In [5]:
# 张量的长度
len(x)

4

In [6]:
# 只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

矩阵

In [7]:
a = torch.arange(20).reshape(5, 4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
# 转置,行变列，列变行
# Wiki: https://zh.wikipedia.org/zh-cn/%E8%BD%AC%E7%BD%AE%E7%9F%A9%E9%98%B5
a.T # 装饰器@property
a.t()

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
# 对称矩阵(symmetric matrix)，转置后结果等于本身
b = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
b

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
b.T == b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

更多维度

In [11]:
# 更多轴的数据结构
x = torch.arange(24).reshape(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
# 相同形状的两个张量，按元素运算后结构相同
a = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# clone可以分配新的内存，相当于一个副本
b = a.clone()
a, a + b

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [13]:
# 两个矩阵的按元素乘法称为Hadamard积（Hadamard product）（数学符号⊙）
a * b

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [14]:
a = 2
x = torch.arange(24).reshape(2, 3, 4)
a, x

(2,
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]))

In [15]:
# 一个数和两个矩阵相加
a + x

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [16]:
# 一个数和两个矩阵相乘
a * x

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [17]:
# 相乘后结果不变
(a * x).shape

torch.Size([2, 3, 4])

In [18]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

In [19]:
# 计算元素的和
x.sum()

tensor(6.)

In [20]:
#任意形状都可以求和
print(b)
print(b.shape)
print(b.sum())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])
tensor(190.)


#### 维度
##### 求和

In [21]:
a = torch.arange(20 * 2, dtype=torch.float32).reshape(2, 5, 4)
print(a)
print(a.sum())

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])
tensor(780.)


In [22]:
# axis参数针对上面reshape的参数，
# 0指第一个参数2的求和
a_sum_axis0 = a.sum(axis=0)
print(a_sum_axis0)
print(a_sum_axis0.shape)

tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]])
torch.Size([5, 4])


In [23]:
# 0指第二个参数5的求和
a_sum_axis1 = a.sum(axis=1)
print(a_sum_axis1)
print(a_sum_axis1.shape)

tensor([[ 40.,  45.,  50.,  55.],
        [140., 145., 150., 155.]])
torch.Size([2, 4])


In [24]:
# 也可以这么干
a.sum(axis=[0, 2])

tensor([ 92., 124., 156., 188., 220.])

##### 求平均值

In [25]:
#两个意义是一样的
print(a.mean())
print(a.sum() / a.numel())

tensor(19.5000)
tensor(19.5000)


In [26]:
a

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [27]:
# 同样，维度的均值也可以这么操作
print(a.mean(axis=0))
print(a.sum(axis=0) / a.shape[0])

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])
tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])


##### 保留维度的求和

In [28]:
print(a.sum(axis=1))
print(a.sum(axis=1, keepdims=True))

tensor([[ 40.,  45.,  50.,  55.],
        [140., 145., 150., 155.]])
tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])


In [29]:
#该方法一般用于广播机制，如果不加该参数会因为维度不对报错
a / a.sum(axis=1, keepdims=True)

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [30]:
# 累加求和
# 该方法好像仅应用于行
# 即第二行的结果是原来的第一行加第二行，后面以此类推
# 此函数不会沿任何轴降低输入张量的维度。
a.cumsum(axis=2)

tensor([[[  0.,   1.,   3.,   6.],
         [  4.,   9.,  15.,  22.],
         [  8.,  17.,  27.,  38.],
         [ 12.,  25.,  39.,  54.],
         [ 16.,  33.,  51.,  70.]],

        [[ 20.,  41.,  63.,  86.],
         [ 24.,  49.,  75., 102.],
         [ 28.,  57.,  87., 118.],
         [ 32.,  65.,  99., 134.],
         [ 36.,  73., 111., 150.]]])

##### 点积

几何论证有点复杂

代码挺简单

In [31]:
y = torch.ones(4, dtype=torch.float32)

In [32]:
print(x)
print(y)

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])


In [33]:
torch.dot(x, y)

tensor(6.)

In [34]:
# 当然可以直接执行元素乘法然后求和，依然求出点积
torch.sum(x * y)

tensor(6.)

#### 矩阵向量积

即矩阵乘法

torch计算挺简单

In [35]:
t1 = torch.arange(4).reshape(2, 2)
t2 = torch.tensor([2, 2])

In [36]:
t1, t2

(tensor([[0, 1],
         [2, 3]]),
 tensor([2, 2]))

In [37]:
torch.mv(t1, t2)

tensor([ 2, 10])

In [38]:
# 线性变换
a[0], x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [39]:
torch.mv(a[0], x)

tensor([ 14.,  38.,  62.,  86., 110.])

复合线性变换


In [40]:
b = torch.ones(4, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [41]:
torch.mm(a[0], b)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

#### 范数

范数是向量或者矩阵的长度

##### L<sub>2</sub>范数

所有的元素做平方后求和，然后开根号，最后做绝对值

如果只有两个就变成勾股定理？

结果为一个标量

In [42]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

##### L<sub>1</sub>范数

向量元素的绝对值之和

torch没有对其包装

In [43]:
torch.abs(u).sum()

tensor(7.)

##### 佛罗贝尼乌斯范数(Frobenius norm)

计算方法是

将矩阵中所有的元素平方和开方的绝对值

In [44]:
t = torch.ones(3, 4)

In [45]:
torch.norm(t)

tensor(3.4641)