### 数据操作

[视频](https://www.bilibili.com/video/BV1CV411Y7i4?p=2) | [教材](https://zh-v2.d2l.ai/chapter_preliminaries/ndarray.html)

In [1]:
import torch

In [2]:
# 张量等于数组,aranage生成一个张量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

shape是访问张量的形状

In [3]:
s = x.shape
s

torch.Size([12])

In [4]:
print(type(s))

<class 'torch.Size'>


numel是元素总数


In [5]:
n = x.numel()
n

12

In [6]:
print(type(n))

<class 'int'>


改变张量形状

In [7]:
# 传入了两个参数，第一个为行第二个为列
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X.shape

torch.Size([3, 4])

In [9]:
torch.numel(X)

12

In [10]:
# 创建全0的张量
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# 创建全1的张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
# 通过直接赋值创建张量
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

##### 运算

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x, y

(tensor([1., 2., 4., 8.]), tensor([2, 2, 2, 2]))

In [14]:
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
# 指数
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [17]:
# 张量连接
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [18]:
# 通过对比可以直接创建二元张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
# 张量求和，结果是一个元素的张量
X.sum()

tensor(66.)

广播

In [20]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(3).reshape((1, 3))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2]]))

In [21]:
# 对于结构不同的张量相加，会复制行或者列为相同的结构后相加
# 如果不能确定复制对象则报错
a + b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

切片

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
# 最后一行
print(X[-1])
# 第一行到第二行，不含第三行
print(X[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [24]:
# 写入
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
# 多个对象写入
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

内存问题

In [26]:
# id方法可以获取变量的内存地址
before = id(Y)
Y = Y + X
id(Y) == before

False

In [27]:
# 使用[:]则可以直接指向变量的内存地址
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

对象转换

In [28]:
# 类型的相互转换
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
# 如果是元素只有1个的标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)